### ISSUE TITLE
✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩

### ISSUE THREAD

**Issue by EvanBacon** [EvanBacon/react-native-flappy-bird#1]
✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨💫🌟⭐️🤩✨

**Comment by rewdt** [comment]
![Screenshot_1556351446](https://user-images.githubusercontent.com/30873429/56846646-950ec880-68c9-11e9-915e-121dd405b1a8.png)
i just cloned and have been trying to view it doesn't seem to work. your help will be greatly apprecited find attached the error message

**Comment by EvanBacon** [comment]
Should work now
